spring:
    application:
      name:  department-service
server:
  port: 8183

#eureka:
    #client:
     # register-with-eureka: true
      #fetch-registry: true
      #service-url:
        #defaultZone: http://localhost:1800/eureka/
    #instance:
      #hostname: server-service